import { F } from "./51";
test("should return correct results", () => {
  expect(F("AMPLUA BEZZAKONIE KRUJOK SILOS ALGEBRA KABLUK KIPIATOK")).toEqual(
    "ALGEBRA AMPLUA BEZZAKONIE KABLUK KIPIATOK KRUJOK SILOS"
  );
  expect(F("PODSTUP KARANDASH PIKAP KARACAN")).toEqual(
    "KARACAN KARANDASH PIKAP PODSTUP"
  );
  expect(F("POLKOVODET PODSTUP OPLOSHNOSTI BESCINSTVO SUFFIX")).toEqual(
    "BESCINSTVO OPLOSHNOSTI PODSTUP POLKOVODET SUFFIX"
  );
});
